# @Author: Haupt Joshua <HauptJ>
# @Date:   02-Apr-2018
# @Email:  josh@hauptj.com
# @Filename: wordpress.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
  # Tasks to setup WordPress database
  # TODO: Refactor variable names

- name: Create new database {{ wp_db_name }}
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  when: wp_new_db == true

- name: Load existing database {{ wp_db_name }}
  block:
    - name: Copy database {{ wp_db_name }} file
      copy:
        src: "{{ wp_db_name }}.sql.bz2"
        dest: /tmp

    - name: Restore database {{ wp_db_user }}
      mysql_db:
        name: "{{ wp_db_name }}"
        state: import
        target: /tmp/{{ wp_db_name }}.sql.bz2

  when: wp_new_db == false

- name: Create new database user {{ wp_db_user }}
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: 'localhost'
    state: present
