---
  # Tasks to setup WordPress database

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create new database {{ mariadb_db_name }}
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
  #when: mariadb_new_db == true
  tags:
    - new

- name: Load existing database {{ mariadb_db_name }} from file {{ mariadb_db_file_name }}
  block:
    - name: Copy database {{ mariadb_db_file_name }}
      copy:
        src: "{{ mariadb_db_backup_dir }}/{{ mariadb_db_file_name }}"
        dest: "/tmp/{{ mariadb_db_file_name }}"

    - name: Restore database {{ mariadb_db_name }}
      mysql_db:
        name: "{{ mariadb_db_name }}"
        state: import
        target: "/tmp/{{ mariadb_db_file_name }}"

  #when: mariadb_new_db == false
  tags:
    - restore

- name: Create new database user {{ mariadb_db_user }}
  mysql_user:
    name: "{{ mariadb_db_user }}"
    password: "{{ mariadb_db_user_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    host: 'localhost'
    state: present
