# @Author: Haupt Joshua <HauptJ>
# @Date:   02-Apr-2018
# @Email:  josh@hauptj.com
# @Filename: wordpress.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 07-Apr-2018

---
  # Tasks to setup WordPress database
  # TODO: Refactor variable names

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create new database {{ maria_db_name }}
  mysql_db:
    name: "{{ maria_db_name }}"
    state: present
  when: mariadb_new_db == true

- name: Load existing database {{ maria_db_name }}
  block:
    - name: Copy database {{ maria_db_name }} file
      copy:
        src: "{{ maria_db_name }}.sql.bz2"
        dest: /tmp

    - name: Restore database {{ maria_db_user }}
      mysql_db:
        name: "{{ maria_db_name }}"
        state: import
        target: /tmp/{{ maria_db_name }}.sql.bz2

  when: mariadb_new_db == false

- name: Create new database user {{ maria_db_user }}
  mysql_user:
    name: "{{ maria_db_user }}"
    password: "{{ maria_db_password }}"
    priv: "{{ maria_db_name }}.*:ALL"
    host: 'localhost'
    state: present
