# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: main.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB repo
  yum_repository:
    name: mariadb
    description: mariadb yum repo
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    enabled: yes

- name: Install MariaDB package
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - MariaDB-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775

- name: Configure SELinux
  include_tasks: selinux.yml
  when: sel_disable == false

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
  notify: restart mariadb
  ignore_errors: true

- name: Setup database
  include_tasks: database.yml
  when: mariadb_wp_db == true

- name: Set MariaDB root user password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: ""
    state: present
  notify: restart mariadb
  when: mariadb_set_root_password == true

- name: Add firewalld rule for MariaDB to open port {{ mariadb_port }}
  firewalld:
    port: "{{ mariadb_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when: mariadb_open_port == true
  ignore_errors: true
